language: "perl"
perl:
    - "5.10"
node_js:
    - "0.12"
    - "0.10"
install: "echo"

script: "perl Configure.pl --backends=moar $NQP_OPTIONS; make test"

branches:
   only:
     - master
     - /smoke-me/

env:
  matrix:
    - NQP_OPTIONS="--gen-moar"
    - NQP_OPTIONS="--gen-moar=master"
    - NQP_OPTIONS="--gen-moar --backends=js,moar"
    - NQP_OPTIONS="--gen-moar=master --backends=js,moar"
