language: perl

os:
    - linux
    - osx

sudo: false

fast_finish: true

install: "echo"
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-6

script:
    - if [[ $TRAVIS_OS_NAME != osx && $NQP_OPTIONS =~ jvm ]]; then sudo -E apt-get install oracle-java9-installer; fi
    - perl Configure.pl $NQP_OPTIONS
    - make test
    - make install

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#perl6-dev"
    on_success: change
    on_failure: always
    template:
      - "NQP build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"


env:
  matrix:
    - NQP_OPTIONS="--gen-moar"
    - NQP_OPTIONS="--gen-moar=master"
    - NQP_OPTIONS="--backends=jvm"

#matrix:
#  allow_failures:
#    - env: NQP_OPTIONS="--backends=jvm"
